### ISSUE TITLE
dpc/rustyhex is not being rebuild daily.

### ISSUE THREAD

**Issue by dpc** [hansjorg/rust-ci#10]
I can schedule manual rebuild, every time I push I get a rebuild, but there seem to be no daily rebuild.

**Comment by am0d** [comment]
Just chiming in to say that none of my projects are being built daily anymore either.
I also seem to be unable to do a manual rebuild - the status icon just keeps spinning.

**Comment by Ogeon** [comment]
I'm having the same problem and it has been like this for a month. My last rebuild was 2014-04-08.

**Comment by brson** [comment]
@hansjorg Do you know what needs to happen to fix the current breakage and how people can help?

**Comment by kud1ing** [comment]
When i trigger a build manualy, the rust-nightly seems to be old:

```
Get:1 http://ppa.launchpad.net/hansjorg/rust/ubuntu/ precise/main rust-nightly amd64 201404180405~0c23140~precise [82.2 MB]
[...]
Unpacking rust-nightly (from .../rust-nightly_201404180405~0c23140~precise_amd64.deb) ...
```

Or is this bound to the time of the commit?

**Comment by hansjorg** [comment]
The launchpad build for precise fails after the required gcc version was bumped some time ago.

The configure script does not take CC/CXX environment variables into consideration, so it's not possible to set an alternative gcc.

Should start building again when this issue is landed:

https://github.com/mozilla/rust/pull/13823

**Comment by ujh** [comment]
In the meantime you can use the official nightlies, but of course you loose the daily triggering: http://bettong.net/2014/05/09/how-to-test-rust-on-travis-ci/

**Comment by am0d** [comment]
Looks like mozilla/rust#13823 is landed now - will the builds start again automatically now?

**Comment by hansjorg** [comment]
Should be fixed now.
