### ISSUE TITLE
Add a "cargo compatible" column

### ISSUE THREAD

**Issue by emberian** [hansjorg/rust-ci#12]
It'd be nice to sort by, and know at a glance, if a given project is compatible with cargo. For now, it's easy to check that just by testing the presence of a Cargo.toml in the root of the repository.

**Comment by hansjorg** [comment]
Good idea. I've added the column to the front page now. Updates every 10 minutes. Going to add it to the search on the project page etc. soon.

**Comment by emberian** [comment]
Awesome, thanks!
