### ISSUE TITLE
Cargo.toml isn't necessarily at the top level of a repository

### ISSUE THREAD

**Issue by huonw** [hansjorg/rust-ci#14]
Cargo supports "metapackages", i.e. a repository that holds multiple `Cargo.toml`s and thus multiple packages. The following is a _possible_ directory structure:

```
.
|-- foo
|   |-- Cargo.toml
|   `-- src
|       `-- lib.rs
`-- foo_macros
    |-- Cargo.toml
    `-- src
        `-- lib.rs
```

i.e. all packages nested. Maybe there could be an explicit `Cargo enabled` check box so that people can indicate support for situations like the above when it can't easily be inferred?

**Comment by hansjorg** [comment]
Didn't know this was supported, thanks for the heads up. I've added a check box for this on add and edit now.
