### ISSUE TITLE
Why are GitHub premissions needed

### ISSUE THREAD

**Issue by SimonSapin** [hansjorg/rust-ci#15]
Related to #9.

Adding a project asks for the following GitHub permissions:
- Personal user data
- Webhooks and services
- Commit statuses
- Deployments
- Organizations and teams

Could you explain why these are needed, when Travis-CI already has the permissions they asked for?

**Comment by hansjorg** [comment]
From the Travis-CI [API documentation](http://docs.travis-ci.com/api/#authentication):

```
To authenticate against Travis CI, you need an API access token.

You can retrieve a token by using a GitHub token to prove who you are.
In the future, we are planning to add a proper OAuth handshake for third party applications.
```
