### ISSUE TITLE
"Unauthorized" error when adding project

### ISSUE THREAD

**Issue by lambda-fairy** [hansjorg/rust-ci#2]
I maintain the [Rose](http://www.rust-ci.org/lfairy/rose) regex library, which is listed on Rust CI.

Unfortunately, when I try to enable the project using the "Get auth token" link, it always fails with the message: "Unauthorized". I have tried revoking and re-authorizing both Rust CI and Travis, to no avail.

Rust CI is listed on my GitHub account, so there is no problem from that end.

Is there anything I've missed? I see many projects working as usual, so there must be something special going on.

**Comment by hansjorg** [comment]
I think this was caused by an error in the Varnish configuration. Could you retry now?

**Comment by lambda-fairy** [comment]
Excellent -- works brilliantly. Many thanks for the fast reply.
