### ISSUE TITLE
No way to remove the outdated docs?

### ISSUE THREAD

**Issue by ArtemGr** [hansjorg/rust-ci#26]
The project http://www.rust-ci.org/sfackler/rust-postgres was removed from rust-ci and yet the outdated docummentation at http://www.rust-ci.org/sfackler/rust-postgres/doc/postgres/ is still available, the search engines will keep pointing to it!

Please remove the documentation when user removes the project!

cf. https://github.com/sfackler/rust-postgres/issues/86

**Comment by hansjorg** [comment]
It was lingering in Varnish cache, sorry about that. Added purging of Varnish on deleting a project now.

**Comment by ArtemGr** [comment]
Thanks!

> Added purging of Varnish on deleting a project now.

That's cool!
