### ISSUE TITLE
Edit description

### ISSUE THREAD

**Issue by ozkriff** [hansjorg/rust-ci#3]
How do i change my project description?

**Comment by hansjorg** [comment]
The description is fetched from Travis each time a build has been triggered, and they fetch it from GitHub. You might have to go to your Travis account page and choose "Sync now" after changing it on GitHub.

**Comment by ozkriff** [comment]
Not works for me: [pic](https://f.cloud.github.com/assets/662976/2028883/c9e4d310-88d7-11e3-99ec-a44e2b64d50c.png)

**Comment by hansjorg** [comment]
My bad, it was only fetched when adding the project. Fixed now. Thanks for reporting!
