### ISSUE TITLE
MARK WEBSITE AS BROKEN

### ISSUE THREAD

**Issue by remram44** [hansjorg/rust-ci#31]
If there is no intention to fix this, please at least mark somewhere that it doesn't work. Making good-intended people lose their time to reach that conclusion isn't nice.

**Comment by carlpaten** [comment]
Bump!

**Comment by hansjorg** [comment]
Now redirects to crates.io.

**Comment by carlpaten** [comment]
<3

**Comment by bstrie** [comment]
Thanks @hansjorg! :)
