### ISSUE TITLE
Documentation css etc no longer works.

### ISSUE THREAD

**Issue by SiegeLord** [hansjorg/rust-ci#8]
`rustdoc` now places the css and documentation inside the `doc` directory, rather than in the individual crates' directories. E.g. from one of my projects:

```
$ ls doc
allegro5  allegro_font  allegro_image  jquery.js  main.css  main.js  normalize.css  search-index.js  src
```

rust-ci doesn't appear to handle those files correctly, resulting in non-functional documentation.

**Comment by hansjorg** [comment]
Updated to work with new file layout now.
