### ISSUE TITLE
Reduce permissions required of my GitHub account

### ISSUE THREAD

**Issue by mgax** [hansjorg/rust-ci#9]
The authorization page says:

> Review permissions
> Repositories - Public only 
> This application will be able to read and write all public repo data. This includes the following:
> - Code
> - Issues
> - Pull requests
> - Wikis
> - Settings
> - Webhooks and services
> - Deploy keys
> 
> [learn more](https://help.github.com/articles/connecting-with-third-party-applications#repositories)

Surely rust-ci doesn't need write access to anything in my account :)

**Comment by hansjorg** [comment]
This was the minimum level required by Travis CI to acquire a token from them through their API, but this seems to have been fixed recently:

https://github.com/travis-ci/travis-ci/issues/1390

I'll look into their new mechanism soon, in the meantime you can work around it by revoking the authorization after you've added your project.
